; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = esp32

[common]
framework = arduino
monitor_speed = 115200
upload_speed = 256000
monitor_filters = esp32_exception_decoder
build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -D FIRMWARE_VERSION='"0.0.1"'


[env:esp32]
platform = espressif32@7.0.1
board = esp32dev
framework = ${common.framework}

board_build.flash_mode = dio
board_build.partitions = huge_app.csv
board_build.psram = disabled

upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
monitor_filters = ${common.monitor_filters}

board_build.f_flash = 80000000L

build_flags =
  ${common.build_flags}
  -D HAL_ESP32
  -D ARDUINO_PARTITION_huge_app
  -D ARDUINO_RUNNING_CORE=1
  -D ARDUINO_EVENT_RUNNING_CORE=1

build_src_filter =
    +<OnStepX.ino>
    +<*.ino>
    +<*.cpp>
    +<*.h>
    +<src/**>
    -<.*/>
    -<lib/>
    -<test/>

[env:esp32_debug]
extends = env:esp32
build_type = debug
build_flags = 
    ${env:esp32.build_flags}
    -D DEBUG
    -D CORE_DEBUG_LEVEL=5
    -D DEBUG_ESP_PORT=Serial
    -O0
    -g3